# swagger: "3.1"
openapi: 3.0.0
info:
  title: Verificable Credential Service Documentation
  description: Verificable Credential Service Api Documentation
  version: "0.2.0"
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: /api
    description: Default Server
  - url: "{protocol}://{environment}:{port}/api"
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      port:
        default: "443"
      environment:
        default: localhost
    description: Custom Server
tags:
  - name: System-Health
    description: Checks API and Blockchain connection status
  - name: Crypto-Management
    description: Crypto utils to be able to tests API
  - name: Authorization-Service
    description: Service that implements OIDC Authorization Server
  - name: Credential-Service
    description: Service that implements Verifiable Credentials Server

paths:
  # Crypto management
  /crypto/keys:
    post:
      tags:
        - Crypto-Management
      responses:
        "200":
          description: OK
  # OIDC Authorization API Service
  /auth/.well-known/openid-configuration:
    get:
      summary: OIDC Configuration
      description: >-
        Returns the static OIDC Configuration object
      tags:
        - Authorization-Service
      operationId: get-configuration
      parameters:
        - name: issuerUri
          in: query
          description: The issuer URI
          required: true
          schema:
            type: string
          example: "https://my.example.issuer/issuer"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OidcConfiguration"
        "404":
          description: Not Found
  /auth/authorize/:
    get:
      summary: Authorization endpoint
      description: Authorization endpoint to send the authorization_request and initiate the authorization flow
      operationId: authorizationRequest
      tags:
        - Authorization-Service
      parameters:
        - in: query
          name: response_type
          description: MUST be code
          schema:
            type: string
          required: true
          example: code
        - in: query
          name: scope
          description: MUST include openid
          schema:
            type: string
          required: true
          example: openid
        - in: query
          name: issuer_state
          description: The state from the issuer
          schema:
            type: string
          required: false
          example: tracker=vcfghhj
        - in: query
          name: state
          description: The state from the client
          schema:
            type: string
          required: false
          example: client-state
        - in: query
          name: client_id
          description: The client identifier
          schema:
            type: string
          required: true
          example: did:key:z2dmzD81cgPx8Vki7JbuuMmFYrWPgYoytykUZ3eyqht1j9KbsEYvdrjxMjQ4tpnje9BDBTzuNDP3knn6qLZErzd4bJ5go2CChoPjd5GAH3zpFJP5fuwSk66U5Pq6EhF4nKnHzDnznEP8fX99nZGgwbAh1o7Gj1X52Tdhf7U4KTk66xsA5r
        - in: query
          name: redirect_uri
          description: The client's redirection endpoint
          schema:
            type: string
          required: true
          example: "openid://example.complete.uri"
        - in: query
          name: nonce
          description: A random value generated by the client
          schema:
            type: string
          required: false
          example: glkFFoisdfEui43
        - in: query
          name: code_challenge
          description: A challenge generated from the code_verifier
          schema:
            type: string
          required: false
          example: YjI0ZTQ4NTBhMzJmMmZhNjZkZDFkYzVhNzlhNGMyZDdjZDlkMTM4YTY4NjcyMTA5M2Q2OWQ3YjNjOGJlZDBlMS AgLQo=
        - in: query
          name: code_challenge_method
          description: The method used to generate the code_challenge
          schema:
            type: string
          required: false
          example: S256
        - in: query
          name: authorization_details
          schema:
            type: string
          required: true
          example: '[{"type":"openid_credential","format":"jwt_vc","types":["VerifiableCredential","VerifiableAttestation","CTWalletSameInTime"]}]'
        - in: query
          name: client_metadata
          schema:
            type: string
          required: false
          example:
            {
              "vp_formats_supported":
                {
                  "jwt_vp": { "alg_values_supported": ["ES256"] },
                  "jwt_vc": { "alg_values_supported": ["ES256"] },
                },
              "response_types_supported": ["vp_token", "id_token"],
              "authorization_endpoint": "openid://",
            }
        - name: issuerUri
          in: query
          description: The issuer URI
          required: true
          schema:
            type: string
          example: "https://my.example.issuer/issuer"
        - name: privateKeyJwk
          in: query
          description: Private Keys in JSON Web Key (JWK) to sign the "request" JWT in the ID_Token request
          required: true
          schema:
            type: string
          example: '{"kty":"EC","x":"ujcuaJoOpnBxYYtlipyFQIahB5GDafNWO1TE2MR7YUI","y":"QOSoMUrerJI_kk5X34ACrmLB9adRstwmCWtdGYa_QKg","crv":"P-256","d":"V2Mgya-Tq13ltrW2JDRDNG3O0rOH6h59bhyARnDTpmQ"}'
        - name: publicKeyJwk
          in: query
          description: Public Key in JSON Web Key (JWK)
          required: true
          schema:
            type: string
          example: '{"kty":"EC","x":"ujcuaJoOpnBxYYtlipyFQIahB5GDafNWO1TE2MR7YUI","y":"QOSoMUrerJI_kk5X34ACrmLB9adRstwmCWtdGYa_QKg","crv":"P-256"}'
      responses:
        # Not Standard
        200:
          description: Response with ID_Token request
          content:
            application/json:
              schema:
                type: object
                properties:
                  location:
                    description: The redirect URI containing the authorization code, state, and additional information
                    type: string
                    example: "openid://client_id=https%3A%2F%2Fmy-issuer.rocks%2Fauth&response_type=id_token&scope=openid&redirect_uri=https%3A%2F%2Fmy-issuer.rocks%2Fauth%2Fdirect_post&request=eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6ImM0S3JlcEpYem1CTVctcW8ybnREQ3drVGdMbTJDYl81ZWFiemtsalRoXzAifQ.eyJpc3MiOiJodHRwczovL215LWlzc3Vlci5yb2Nrcy9hdXRoIiwiYXVkIjoiZGlkOmtleTp6MmRtekQ4MWNnUHg4VmtpN0pidXVNbUZZcldQZ1lveXR5a1VaM2V5cWh0MWo5S2JzRVl2ZHJqeE1qUTR0cG5qZTlCREJUenVORFAza25uNnFMWkVyemQ0Yko1Z28yQ0Nob1BqZDVHQUgzenBGSlA1ZnV3U2s2NlU1UHE2RWhGNG5Lbkh6RG56bkVQOGZYOTluWkdnd2JBaDFvN0dqMVg1MlRkaGY3VTRLVGs2NnhzQTVyIiwiZXhwIjoxNTg5Njk5MTYyLCJyZXNwb25zZV90eXBlIjoiaWRfdG9rZW4iLCJyZXNwb25zZV9tb2RlIjoiZGlyZWN0X3Bvc3QiLCJjbGllbnRfaWQiOiJodHRwczovL215LWlzc3Vlci5yb2Nrcy9hdXRoIiwicmVkaXJlY3RfdXJpIjoiaHR0cHM6Ly9teS1pc3N1ZXIucm9ja3MvYXV0aC9kaXJlY3RfcG9zdCIsInNjb3BlIjoib3BlbmlkIiwibm9uY2UiOiJuLTBTNl9XekEyTWoifQ.Vg615ydUGWQBM_o0mSoBePYTPyplbmcFv1oWa2mF3K-CeB9n6biCqmP-1w2jBLxSHVbIJlz_Ta0hc9pFWsewRQ"
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /auth/direct_post:
    post:
      summary: Direct Post Endpoint
      description: Endpoint for receiving the ID token in an x-www-form-urlencoded payload and returning a redirect with the code and state parameters.
      operationId: directPost
      tags:
        - Authorization-Service
      requestBody:
        description: ID token payload
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                issuerUri:
                  description: The issuer URI
                  type: string
                  example: "https://my.example.issuer/issuer"
                privateKeyJwk:
                  description: Private Keys in JSON Web Key (JWK) to sign the "request" JWT in the ID_Token request
                  type: string
                  example: '{"kty":"EC","x":"ujcuaJoOpnBxYYtlipyFQIahB5GDafNWO1TE2MR7YUI","y":"QOSoMUrerJI_kk5X34ACrmLB9adRstwmCWtdGYa_QKg","crv":"P-256","d":"V2Mgya-Tq13ltrW2JDRDNG3O0rOH6h59bhyARnDTpmQ"}'
                id_token:
                  type: string
                  description: ID Token signed by the DID document's authentication key. This will be used to prove the control of the DID.
              required:
                - issuerUri
                - privateKeyJwk
      responses:
        200:
          description: Successfully processed the ID token and redirecting with the code and state parameters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  location:
                    type: string
                    example: "openid://?code=SplxlOBeZQQYbYS6WxSbIA&state=client-state"
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /auth/token:
    post:
      summary: Token Endpoint
      description: Endpoint for exchanging the authorization code for an access token.
      operationId: exchangeToken
      tags:
        - Authorization-Service
      requestBody:
        description: Authorization code and other required parameters
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  description: MUST be authorization_code or urn:ietf:params:oauth:grant-type:pre-authorized_code
                  example: authorization_code
                client_id:
                  type: string
                  description: The client identifier
                  example: "did:key:z2dmzD81cgPx8Vki7JbuuMmFYrWPgYoytykUZ3eyqht1j9KbsEYvdrjxMjQ4tpnje9BDBTzuNDP3knn6qLZErzd4bJ5go2CChoPjd5GAH3zpFJP5fuwSk66U5Pq6EhF4nKnHzDnznEP8fX99nZGgwbAh1o7Gj1X52Tdhf7U4KTk66xsA5r"
                code:
                  type: string
                  description: The authorization code
                  example: SplxlOBeZQQYbYS6WxSbIA
                pre-authorized_code:
                  type: string
                  description: The pre-authorization code
                  example: eyJhbGciOiJFUzI1NiIsImtpZCI6ImF3emcxdU44WUFpUTR6RHVpM0tEN2ZQV1F3N093dTlyTHZGY1YxNlBaYU0ifQ.eyJhdXRob3JpemF0aW9uX2RldGFpbHMiOlt7InR5cGUiOiJvcGVuaWRfY3JlZGVudGlhbCIsImZvcm1hdCI6Imp3dF92YyIsImxvY2F0aW9ucyI6WyJodHRwczovL2lkZW50ZnktYmFja2VuZC1zdGFnaW5nLTJmZDg0M2U2MzdlOC5oZXJva3VhcHAuY29tLzQiXSwidHlwZXMiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJWZXJpZmlhYmxlQXR0ZXN0YXRpb24iLCJDVFdhbGxldFNhbWVQcmVBdXRob3Jpc2VkIl19XSwiaWF0IjoxNzAwMjIwOTk3LCJleHAiOjE3MDAyMjEyOTcsImlzcyI6Imh0dHBzOi8vaWRlbnRmeS1iYWNrZW5kLXN0YWdpbmctMmZkODQzZTYzN2U4Lmhlcm9rdWFwcC5jb20vNCIsImF1ZCI6Imh0dHBzOi8vaWRlbnRmeS1iYWNrZW5kLXN0YWdpbmctMmZkODQzZTYzN2U4Lmhlcm9rdWFwcC5jb20vNC9hdXRob3JpemUiLCJzdWIiOiJkaWQ6ZWJzaTp6SlEyalV4eGdEdlhBNlRlR2F0blJiaSJ9.eRTo-3PrVX_HyLsM5Jz8IJpgbFRaCXFTLqoNqdi02gelAtl0jJq3WuNp34RrF9vYaD1ZbPZrkGZcudiA1bSKAw
                code_verifier:
                  type: string
                  description: The code verifier for the PKCE request
                  example: random-secret
                  # this service CUSTOM
                issuerUri:
                  description: The issuer URI
                  type: string
                  example: "https://my.example.issuer/issuer"
                privateKeyJwk:
                  description: Private Keys in JSON Web Key (JWK) to sign the "request" JWT in the ID_Token request
                  type: string
                  example: '{"kty":"EC","x":"ujcuaJoOpnBxYYtlipyFQIahB5GDafNWO1TE2MR7YUI","y":"QOSoMUrerJI_kk5X34ACrmLB9adRstwmCWtdGYa_QKg","crv":"P-256","d":"V2Mgya-Tq13ltrW2JDRDNG3O0rOH6h59bhyARnDTpmQ"}'
                publicKeyJwk:
                  description: Public Key in JSON Web Key (JWK)
                  type: string
                  example: '{"kty":"EC","x":"ujcuaJoOpnBxYYtlipyFQIahB5GDafNWO1TE2MR7YUI","y":"QOSoMUrerJI_kk5X34ACrmLB9adRstwmCWtdGYa_QKg","crv":"P-256"}'
              required:
                - grant_type
                - privateKeyJwk
                - publicKeyJwk
                - issuerUri
      responses:
        200:
          description: Successfully exchanged the authorization code for an access token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: "eyJhbGciOiJSUzI1NiIsInR5cCI6Ikp..sHQ"
                  token_type:
                    type: string
                    example: bearer
                  expires_in:
                    type: integer
                    example: 86400
                  id_token:
                    type: string
                    example: "eyJodHRwOi8vbWF0dHIvdGVuYW50L..3Mz"
                  c_nonce:
                    type: string
                    example: "PAPPf3h9lexTv3WYHZx8ajTe"
                  c_nonce_expires_in:
                    type: integer
                    example: 86400
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  # Credential Service
  /credentials:
    post:
      summary: Credentials Endpoint
      description: Endpoint for requesting credentials.
      operationId: requestCredentials
      tags:
        - Credential-Service
      requestBody:
        description: Credential request parameters
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                types:
                  type: array
                  items:
                    type: string
                  description: Credential types requested
                  example:
                    [
                      "VerifiableCredential",
                      "VerifiableAttestation",
                      "CTWalletSameInTime",
                    ]
                format:
                  type: string
                  description: Format of the returned credentials
                  example: jwt_vc
                proof:
                  type: object
                  properties:
                    proof_type:
                      type: string
                      enum:
                        - jwt
                      example: jwt
                    jwt:
                      type: string
                      minLength: 20
                      pattern: ^ey
                      example: eyJ0eXAiOiJvcGVuaWQ0dmNpLXByb29mK2p3dCIsImFsZyI6IkVTMjU2Iiwia2lkIjoiZGlkOmtleTp6MmRtekQ4MWNnUHg4VmtpN0pidXVNbUZZcldQZ1lveXR5a1VaM2V5cWh0MWo5S2JzRVl2ZHJqeE1qUTR0cG5qZTlCREJUenVORFAza25uNnFMWkVyemQ0Yko1Z28yQ0Nob1BqZDVH (...) DNrbm42cUxaRXJ6ZDRiSjVnbzJDQ2hvUGpkNUdBSDN6cEZKUDVmdXdTazY2VTVQcTZFaEY0bktuSHpEbnpuRVA4Zlg5OW5aR2d3YkFoMW83R2oxWDUyVGRoZjdVNEtUazY2eHNBNXIiLCJhdWQiOiJodHRwczovL215LWlzc3Vlci5yb2Nrcy9hdXRoIiwiZXhwIjoxNTg5Njk5OTYyLCJub25jZSI6IlBBUFBmM2g5bGV4VHYzV1lIWng4YWpUZSJ9.1AK6J-nxkNvQiRehrP7Z3GmXEn-1I7na1ttIMr5cX_nfKSiMCN2-RxY01zAnB-JQ-l5sZEmzWiuvKgRzCD7fUA
                  required:
                    - proof_type
                    - jwt
                issuerUri:
                  description: The issuer URI
                  type: string
                  example: "https://my.example.issuer/issuer"
                issuerDid:
                  description: The issuer DID
                  type: string
                  example: "did:ebsi:zvHWX359A3CvfJnCYaAiAde"
                privateKeyJwk:
                  $ref: "#/components/schemas/JwkPrivate"
                  description: Private Keys in JSON Web Key (JWK) to sign the VC
                  example:
                    kty: EC
                    x: ujcuaJoOpnBxYYtlipyFQIahB5GDafNWO1TE2MR7YUI
                    y: QOSoMUrerJI_kk5X34ACrmLB9adRstwmCWtdGYa_QKg
                    crv: P-256
                    d: V2Mgya-Tq13ltrW2JDRDNG3O0rOH6h59bhyARnDTpmQ
                publicKeyJwk:
                  $ref: "#/components/schemas/JwkPublic"
                  description: Public Key in JSON Web Key (JWK)
                  example:
                    kty: EC
                    x: ujcuaJoOpnBxYYtlipyFQIahB5GDafNWO1TE2MR7YUI
                    y: QOSoMUrerJI_kk5X34ACrmLB9adRstwmCWtdGYa_QKg
                    crv: P-256
            encoding:
              types:
                style: form
                explode: true
      responses:
        200:
          description: Successfully issued credential
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/CredentialResponse"
                  - $ref: "#/components/schemas/DeferredCredentialResponse"
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - bearerAuth: []
  /credential_deferred:
    post:
      summary: Deferred Credentials Endpoint
      description: Endpoint for requesting deferred credentials.
      operationId: requestDeferredCredentials
      tags:
        - Credential-Service
      requestBody:
        description: Deferred Credential request parameters
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                issuerUri:
                  description: The issuer URI
                  type: string
                  example: "https://my.example.issuer/issuer"
                issuerDid:
                  description: The issuer DID
                  type: string
                  example: "did:ebsi:zvHWX359A3CvfJnCYaAiAde"
                privateKeyJwk:
                  $ref: "#/components/schemas/JwkPrivate"
                  description: Private Keys in JSON Web Key (JWK) to sign the VC
                  example:
                    kty: EC
                    x: ujcuaJoOpnBxYYtlipyFQIahB5GDafNWO1TE2MR7YUI
                    y: QOSoMUrerJI_kk5X34ACrmLB9adRstwmCWtdGYa_QKg
                    crv: P-256
                    d: V2Mgya-Tq13ltrW2JDRDNG3O0rOH6h59bhyARnDTpmQ
                publicKeyJwk:
                  $ref: "#/components/schemas/JwkPublic"
                  description: Public Key in JSON Web Key (JWK)
                  example:
                    kty: EC
                    x: ujcuaJoOpnBxYYtlipyFQIahB5GDafNWO1TE2MR7YUI
                    y: QOSoMUrerJI_kk5X34ACrmLB9adRstwmCWtdGYa_QKg
                    crv: P-256
            encoding:
              types:
                style: form
                explode: true
      responses:
        200:
          description: Successfully issued credential
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/CredentialResponse"
                  - $ref: "#/components/schemas/DeferredCredentialResponse"

        400:
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - bearerAuth: []
  /credentials/status:
    post:
      summary: Status Credentials Endpoint
      description: Endpoint for requesting status credentials.
      operationId: requestStatusCredentials
      tags:
        - Credential-Service
      requestBody:
        description: Status Credential request parameters
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                statusList:
                  type: string
                  description: Encoded bitstring list according to https://www.w3.org/TR/2023/WD-vc-status-list-20230427/
                listId:
                  type: string
                  description: Identifier of the StatusList2021 in the Backend
                revocationType:
                  type: string
                  enum:
                    - StatusList2021
                  description: Data structure used to store the revocation information. Only StatusList2021 is allowed
                statusPurpose:
                  type: string
                  enum:
                    - revocation
                    - suspension
                  description: The status purpose, which can be "revocation" or "suspension"
                issuerUri:
                  description: The issuer URI
                  type: string
                  example: "https://my.example.issuer/issuer"
                issuerDid:
                  description: The issuer DID
                  type: string
                  example: "did:ebsi:zvHWX359A3CvfJnCYaAiAde"
                privateKeyJwk:
                  $ref: "#/components/schemas/JwkPrivate"
                  description: Private Keys in JSON Web Key (JWK) to sign the VC
                  example:
                    kty: EC
                    x: ujcuaJoOpnBxYYtlipyFQIahB5GDafNWO1TE2MR7YUI
                    y: QOSoMUrerJI_kk5X34ACrmLB9adRstwmCWtdGYa_QKg
                    crv: P-256
                    d: V2Mgya-Tq13ltrW2JDRDNG3O0rOH6h59bhyARnDTpmQ
            encoding:
              types:
                style: form
                explode: true
      responses:
        200:
          description: Successfully issued credential
          content:
            text/plain:
              schema:
                type: string
                description: The Status VC
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Health:
      title: Health
      type: object
      properties:
        api:
          type: string
          example: "OK"
        blockchain:
          type: object
          properties:
            status:
              type: string
              example: "OK"
            currentBlockNumber:
              type: number
              example: 6
            network:
              type: object
              properties:
                chainId:
                  type: number
                  example: 1337
                name:
                  type: string
                  example: "Ganache"
        contract:
          type: object
          properties:
            name:
              type: string
              example: TokenManager
            address:
              type: string
              example: "0xA89B32EF61C658c0594d4136BB94aA6c236d2555"
            status:
              type: boolean
              example: true
            deployedAt:
              type: object
              properties:
                block:
                  type: number
                  example: 6
                blockHash:
                  type: string
                  example: "0xb321643f5b7871bc5c9a6e101f71ee02cf79b0f0dbd939fea5426290a90b6341"
                Date:
                  type: string
                  example: "2022-09-15T07:02:35.000Z"
    CredentialResponse:
      type: object
      properties:
        format:
          type: string
          example: jwt_vc
        credential:
          type: string
          example: "LUpixVCWJk0eOt4CXQe1NXK....WZwmhmn9OQp6YxX0a2L"
        c_nonce:
          type: string
          example: "fGFF7UkhLa"
        c_nonce_expires_in:
          type: integer
          example: 86400
    DeferredCredentialResponse:
      type: object
      properties:
        acceptance_token:
          type: string
          example: eyJ0eXAiOiJKV1QiLCJhbGci..zaEhOOXcifQ
        c_nonce:
          type: string
          example: "fGFF7UkhLa"
        c_nonce_expires_in:
          type: integer
          example: 86400
      required:
        - acceptance_token
    OidcConfiguration:
      type: object
      properties:
        issuer:
          type: string
        authorization_endpoint:
          type: string
        token_endpoint:
          type: string
        jwks_uri:
          type: string
        scopes_supported:
          type: array
          items:
            type: string
        response_types_supported:
          type: array
          items:
            type: string
        response_modes_supported:
          type: array
          items:
            type: string
        grant_types_supported:
          type: array
          items:
            type: string
        subject_types_supported:
          type: array
          items:
            type: string
        id_token_signing_alg_values_supported:
          type: array
          items:
            type: string
        request_object_signing_alg_values_supported:
          type: array
          items:
            type: string
        request_parameter_supported:
          type: boolean
        request_uri_parameter_supported:
          type: boolean
        token_endpoint_auth_methods_supported:
          type: array
          items:
            type: string
        vp_formats_supported:
          type: object
          properties:
            jwt_vp:
              type: object
              properties:
                alg_values_supported:
                  type: array
                  items:
                    type: string
            jwt_vc:
              type: object
              properties:
                alg_values_supported:
                  type: array
                  items:
                    type: string
        subject_syntax_types_supported:
          type: array
          items:
            type: string
        subject_trust_frameworks_supported:
          type: array
          items:
            type: string
        id_token_types_supported:
          type: array
          items:
            type: string
      title: OidcConfiguration
    JwkPrivate:
      type: object
      required:
        - kty
      properties:
        kty:
          type: string
          description: Key type (e.g., RSA, EC)
          enum:
            - RSA
            - EC
        # RSA properties
        n:
          type: string
          description: RSA modulus (required for RSA)
        e:
          type: string
          description: RSA public exponent (required for RSA)
        d:
          type: string
          description: RSA private exponent (required for RSA private keys)
        p:
          type: string
          description: RSA secret prime factor (required for RSA private keys)
        q:
          type: string
          description: RSA secret prime factor (required for RSA private keys)
        dp:
          type: string
          description: RSA Chinese Remainder Theorem (CRT) coefficient (required for RSA private keys)
        dq:
          type: string
          description: RSA CRT coefficient (required for RSA private keys)
        qi:
          type: string
          description: RSA CRT coefficient (required for RSA private keys)
        # EC properties
        crv:
          type: string
          description: Elliptic curve name (e.g., P-256, P-384, P-521) (required for EC)
        x:
          type: string
          description: Elliptic curve x-coordinate (required for EC)
        y:
          type: string
          description: Elliptic curve y-coordinate (required for EC)
        # d:
        #   type: string
        #   description: Elliptic curve private key (required for EC private keys)
        kid:
          type: string
          description: Key ID, a unique identifier for the key
        alg:
          type: string
          description: Algorithm intended for use with the key (e.g., RS256, ES256)
        use:
          type: string
          description: Public key use (e.g., sig for signature, enc for encryption)
    JwkPublic:
      type: object
      required:
        - kty
      properties:
        kty:
          type: string
          description: Key type (e.g., RSA, EC)
          enum:
            - RSA
            - EC
        # RSA properties
        n:
          type: string
          description: RSA modulus (required for RSA)
        e:
          type: string
          description: RSA public exponent (required for RSA)
        # EC properties
        crv:
          type: string
          description: Elliptic curve name (e.g., P-256, P-384, P-521) (required for EC)
        x:
          type: string
          description: Elliptic curve x-coordinate (required for EC)
        y:
          type: string
          description: Elliptic curve y-coordinate (required for EC)
        kid:
          type: string
          description: Key ID, a unique identifier for the key
        alg:
          type: string
          description: Algorithm intended for use with the key (e.g., RS256, ES256)
        use:
          type: string
          description: Public key use (e.g., sig for signature, enc for encryption)
    JWK:
      type: object
      required:
        - kty
      properties:
        kty:
          type: string
          description: Key type (e.g., RSA, EC)
        alg:
          type: string
          description: Algorithm (e.g., RS256, ES256)
        use:
          type: string
          description: Public key use parameter (e.g., sig, enc)
        kid:
          type: string
          description: Key ID
        x5u:
          type: string
          description: X.509 URL
        x5c:
          type: array
          items:
            type: string
          description: X.509 certificate chain
        x5t:
          type: string
          description: X.509 certificate SHA-1 thumbprint
        x5t#S256:
          type: string
          description: X.509 certificate SHA-256 thumbprint
        n:
          type: string
          description: RSA modulus
        e:
          type: string
          description: RSA public exponent
        p:
          type: string
          description: RSA secret prime factor (should not be shared)
        q:
          type: string
          description: RSA secret prime factor (should not be shared)
        dp:
          type: string
          description: RSA Chinese Remainder Theorem (CRT) coefficient (should not be shared)
        dq:
          type: string
          description: RSA CRT coefficient (should not be shared)
        qi:
          type: string
          description: RSA CRT coefficient (should not be shared)
        crv:
          type: string
          description: Elliptic curve name (e.g., P-256, P-384, P-521)
        x:
          type: string
          description: Elliptic curve x-coordinate
        y:
          type: string
          description: Elliptic curve y-coordinate
        d:
          type: string
          description: Elliptic curve private key (should not be shared) OR RSA private exponent (should not be shared)
    # HTTP ERROR
    Error:
      type: object
      properties:
        error:
          type: string
        error_description:
          type: string
